### PR TITLE
Potential remove fix and comprehensive CutNode tests!

### LINKED ISSUE #157: Remove doesn't work correctly!
As requested on 10/17 at 10:19 AM EST, CutNode.ts' remove method needs to be reworked. Currently, in the case that the current node is the smallest node that contains the passed in Point... the parent has absolutely no idea and nothing happens. 

The parent must know which of their children is being deleted and must know how to update its children accordingly. As such the algorithm must work a level deeper in advance. 

Delete mode writers are in shambles! This cannot go on any longer!

### PR DESCRIPTION
**Pull request by ghost**
Looking for review ASAP

### CODE REVIEW

**Review by DawnTheWitch — APPROVED** [review]
I did my best to read through it as best as I could. To me this makes sense and should work. I spent way too long rereading it to make sure I understood it.

File: src/AEG/CutNode.ts [hunk 1]
```diff
@@ -123,36 +123,48 @@ export class CutNode {
...
             }
-            //if the point is not contained within any children nodes, delete this node
-            if (isSmallest) {
-                //What to do to remove this node?
-                return true;
-            }
         }
-
         return false;
     }
```
Comment (AnushaTiwari5) [inline src/AEG/CutNode.ts:170]: What do you do if the point is contained in the cut, but not in any children of the cut/the cut doesn't have any children?

Comment (DawnTheWitch) [reply src/AEG/CutNode.ts:170]: I might be misunderstanding as well but wouldn't this solve that? And for when the cut doesn't have any children lines 137-143 handle that
image

Comment (AnushaTiwari5) [reply src/AEG/CutNode.ts:170]: Aren't lines 136 - 166 the for loop with stuff happening if any child contain the point? I was wondering what happen if we don't enter that loop/exit that loop without any children containing the point. 
For example, in a situation like in the ss below, the point is within the cut but not within any of the children. So if remove is called on the cut, it would pass through the for loop without anything happening because the if on line 137 would return false
image

Comment (DawnTheWitch) [reply src/AEG/CutNode.ts:170]: I'm pretty sure with what we talked about this function was meant to be used on the parent of the item you want to delete, that way you can access the to be deleted child easier. But that does also make me realize that 131-133 shouldn't include logic to remove the sheet since there's really no way to remove the item itself here

Comment (AnushaTiwari5) [reply src/AEG/CutNode.ts:170]: Ohh that does make more sense then, thank you. I think we do need the ellipse === null check to avoid instance of TS screaming at us that ellipse might be null. That happens if you sometimes if you don't explicitly check. I'm not sure about the containsPoint check though, because ideally wouldn't we always call this assuming it does contain the point?
