### PR TITLE
verify() method and toString() fix

### LINKED ISSUE #52: verify AEG: ensure all AEG children are inside their parents and do not overlap on same level.

### PR DESCRIPTION
**Pull request by ghost**
toString() corrections were put in so I had something to make a pull request for so I could merge master into this branch

### CODE REVIEW

**Review by James-Oswald — APPROVED** [review]

File: src/AEG/AEGTree.ts [hunk 1]
```diff
@@ -12,13 +12,45 @@ export class AEGTree {
...
+            ) {
+                return false;
+            }
+
+            //Check for overlaps on the same level
+            for (let j = 0; j < currentCut.children.length; j++) {
+                if (this.overlaps(currentCut.children[i], currentCut.children[j])) {
+                    return false;
+                }
+            }
```
Comment (James-Oswald) [inline src/AEG/AEGTree.ts:51]: This will check if a child overlaps with itself, returning false every time. additionally, it's extremely inefficient since it checks overlaps of objects twice overlaps is a symmetric relation, i.e., `overlaps(a,b) == overlaps(b,a)` hence you only need to check one of them. You can *probably* fix both of these issues by only checking the upper triangular of the pairing matrix this setup generates, by starting the second loop at `i+1` instead of 0
```suggestion
            for (let j = i+1; j < currentCut.children.length; j++) {
                if (this.overlaps(currentCut.children[i], currentCut.children[j])) {
                    return false;
                }
            }
```

File: src/AEG/AEGTree.ts [hunk 2]
```diff
@@ -12,13 +12,45 @@ export class AEGTree {
...
+                return false;
+            }
+
+            //Check one level deeper if the child is a CutNode
+            if (
+                currentCut.children[i] instanceof CutNode &&
+                !this.verifyAEG(currentCut.children[i] as CutNode)
+            ) {
+                return false;
+            }
```
Comment (James-Oswald) [inline src/AEG/AEGTree.ts:44]: I would make it more obvious this is your recursive case by moving this into its own secondary loop after this loop.

**Review by James-Oswald — CHANGES_REQUESTED** [review]

**Review by James-Oswald — APPROVED** [review]
